# Generated by Django 4.1.7 on 2023-03-21 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="produit",
            name="countries",
            field=models.TextField(default="france"),
        ),
        migrations.AddField(
            model_name="produit",
            name="marque",
            field=models.TextField(default="marque"),
        ),
        migrations.AddField(
            model_name="produit", name="name", field=models.TextField(default="toto"),
        ),
        migrations.AddField(
            model_name="produit",
            name="nutri_score",
            field=models.TextField(default="a"),
        ),
    ]
